import { AnimatePresence } from 'framer-motion'
import type { Metadata } from 'next'
import { Geist, Geist_Mono as GeistMono } from 'next/font/google'
import { CartProvider } from '~/hooks/CartContext'
import './globals.css'

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

const geistMono = GeistMono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-auto max-w-5xl bg-background p-8 antialiased`}
      >
        <AnimatePresence mode="wait">
          <CartProvider>{children}</CartProvider>
        </AnimatePresence>
      </body>
    </html>
  )
}
